repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: forbid-crlf # Forbid files containing CRLF end-lines to be committed
  - repo: local
    hooks:
      - id: lint
        name: Lint Using Flake8
        language: system
        types: [python]
        files: ^vim_eof_comment/.*\.py$
        entry: make lint
        verbose: true
      - id: stubgen
        name: Run stubgen
        language: system
        types: [python]
        files: ^vim_eof_comment/.*\.py$
        entry: make stubs
        verbose: true
